INSERT INTO sizes VALUES
(NULL, '4US'),
(NULL, '4.5US'),
(NULL, '5US'),
(NULL, '5.5US'),
(NULL, '6US'),
(NULL, '6.5US'),
(NULL, '7US'),
(NULL, '7.5US'),
(NULL, '8US'),
(NULL, '8.5US'),
(NULL, '9US'),
(NULL, '9.5US'),
(NULL, '10US'),
(NULL, '10.5US'),
(NULL, '11US'),
(NULL, '11.5US'),
(NULL, '12US'),
(NULL, '12.5US'),
(NULL, '13US'),
(NULL, 'XS'),
(NULL, 'S'),
(NULL, 'M'),
(NULL, 'L'),
(NULL, 'XL');

INSERT INTO provinces VALUES
(NULL, 'Buenos Aires'),
(NULL, 'CABA'),
(NULL, 'Córdoba'),
(NULL, 'Jujuy'),
(NULL, 'Tierra del Fuego'),
(NULL, 'Río Negro'),
(NULL, 'Chubut'),
(NULL, 'La Pampa'),
(NULL, 'Neuquén'),
(NULL, 'Mendoza'),
(NULL, 'San Luis'),
(NULL, 'San Juan'),
(NULL, 'Santa Fe'),
(NULL, 'Tucumán'),
(NULL, 'Corrientes'),
(NULL, 'Formosa'),
(NULL, 'Chaco'),
(NULL, 'Salta'),
(NULL, 'Misiones'),
(NULL, 'Santa Cruz'),
(NULL, 'Entre Ríos'),
(NULL, 'Santiago del Estero'),
(NULL, 'Catamarca'),
(NULL, 'La Rioja');

INSERT INTO brands VALUES
(NULL, 'Nike'),
(NULL, 'Nike SB'),
(NULL, 'Adidas'),
(NULL, 'New Balance'),
(NULL, 'Reebok'),
(NULL, 'Anti Social Social Club'),
(NULL, 'Supreme'),
(NULL, 'BAPE'),
(NULL, 'Vlone'),
(NULL, 'OVO'),
(NULL, 'Tommy Hilfiger');

INSERT INTO models VALUES
(NULL, 'Dunk Low'),
(NULL, 'Dunk Mid'),
(NULL, 'Dunk High'),
(NULL, 'Dunk SB Low'),
(NULL, 'Dunk SB Mid'),
(NULL, 'Dunk SB High'),
(NULL, 'Air Jordan 1 Low'),
(NULL, 'Air Jordan 1 Mid'),
(NULL, 'Air Jordan 1 High'),
(NULL, 'Air Jordan 2'),
(NULL, 'Air Jordan 3'),
(NULL, 'Air Jordan 4'),
(NULL, 'Air Jordan 6'),
(NULL, 'Air Max 1'),
(NULL, 'Air Max 97'),
(NULL, 'Air Max 1/97'),
(NULL, 'Yeezy 350'),
(NULL, 'Yeezy 350 V2'),
(NULL, 'Yeezy 380'),
(NULL, 'Yeezy 550'),
(NULL, 'Yeezy 700'),
(NULL, 'Yeezy 700 V2'),
(NULL, 'Yeezy 700 V3'),
(NULL, 'Yeezy 700 MNVN'),
(NULL, 'Yeezy Slides'),
(NULL, 'Tee-Shirt'),
(NULL, 'Long Sleeves Tee-Shirt');

INSERT INTO cities VALUES
(1900, 'La Plata'),
(1902, 'La Plata'),
(1904, 'La Plata'),
(1906, 'La Plata'),
(1912, 'La Plata'),
(1914, 'La Plata'),
(1926, 'La Plata'),
(1228, 'CABA'),
(1406, 'CABA'),
(1428, 'CABA'),
(1832, 'Lomas de Zamora'),
(5000, 'Córdoba'),
(4600, 'San Salvador de Jujuy'),
(9410, 'Ushuaia'),
(8500, 'Viedma'),
(9103, 'Rawson'),
(6300, 'Santa Rosa'),
(8300, 'Neuquén'),
(5500, 'Mendoza'),
(5700, 'San Luis'),
(5400, 'San Juan'),
(1689, 'Rosario'),
(4000, 'San Miguel de Tucumán'),
(3197, 'Corrientes'),
(3600, 'Formosa'),
(3500, 'Resistencia'),
(4400, 'Salta'),
(3300, 'Posadas'),
(9400, 'Río Gallegos'),
(3100, 'Paraná'),
(4200, 'Santiago del Estero'),
(4700, 'San Fernando del Valle de Catamarca'),
(5300, 'La Rioja');

INSERT INTO clients VALUES
(NULL, 'Ezequiel Camino', 'DNI', 40251162, 'Puerto Madryn 1648', 1, 1832),
(NULL, 'Brandon Maidana', 'DNI', 11111111, 'La Plata 123', 1, 1902),
(NULL, 'Cosme Fulanito', 'DNI', 12345678, 'Calle Falsa 123', 13, 1689);

INSERT INTO products VALUES
(NULL, 'Calzado', 2, 4, 'ACG Terra', NULL, 10, 250),
(NULL, 'Calzado', 1, 14, 'Travis Scott Saturn Gold', NULL, 12, 300),
(NULL, 'Indumentaria', 7, 26, 'Undercover Face Black', NULL, 23, 100);

INSERT INTO orders(order_id, client_id, total) VALUES
(NULL, 1, 350),
(NULL, 2, 300);

INSERT INTO order_detail VALUES
(1, 1, 1),
(1, 3, 1),
(2, 2, 1);